Controllers/ProfilesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NotMyShows.Data;
using NotMyShows.Models;
using NotMyShows.Services;
using NotMyShows.ViewModel;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace NotMyShows.Controllers
{
    [Authorize]
    public class ProfilesController : Controller
    {
        readonly SeriesContext db;
        readonly private IWebHostEnvironment _env;
        private readonly IUserProfileService _userProfileService;
        private readonly ISeriesService _seriesService;
        public ProfilesController(SeriesContext context, IWebHostEnvironment env, IUserProfileService userProfileService, ISeriesService seriesService)
        {
            db = context;
            _env = env;
            _userProfileService = userProfileService;
            _seriesService = seriesService;
        }
        public async Task<IActionResult> Profile(int Id)
        {
            UserProfileViewModel model = await _userProfileService.GetUserProfileAsync(Id);
            if(model == null)
            {
                return BadRequest();
            }
            return View("UserProfile", model);
        }
        public async Task<string> GetUserNameById(int Id)
        {
            var profile = await db.UserProfiles.Select(p => new { Id = p.Id, Name = p.User.UserName }).AsNoTracking().FirstOrDefaultAsync(x => x.Id == Id);
            return profile.Name;
        }
        public async Task<int> GetUserProfileId()
        {
            string UserSub = User.GetSub();
            UserProfile profile = await db.UserProfiles.FirstOrDefaultAsync(x => x.UserId == UserSub);
            return profile.Id;
        }
        public async Task<IActionResult> Episode(int EpisodeId)
        {
            EpisodeViewModel model = await _seriesService.GetEpisodeAsync(EpisodeId);
            return View(model);
        }
        public async Task<IActionResult> Friends()
        {
            FriendsViewModel model = await _userProfileService.GetFriends();
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddComment(string CommentText, int EpisodeId)
        {
            await _userProfileService.AddComment(CommentText, EpisodeId);
            return Json("Success");
        }
        [HttpPost]
        public async Task AddFriend(int FriendId)
        {
            await _userProfileService.AddFriend(FriendId);
        }
        [HttpPost]
        public async Task RemoveFriend(int FriendId)
        {
            await _userProfileService.RemoveFriend(FriendId);
        }
        public async Task<IActionResult> Series(int SeriesId)
        {

            SeriesViewModel model = await _seriesService.GetSeriesAsync(SeriesId);
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> SelectWatchStatus(int SeriesId, string StatusName)
        {
            await _userProfileService.SelectWatchStatus(SeriesId, StatusName);
            return Json("Success");
        }
        [HttpPost]
        public async Task<IActionResult> CheckEpisodes(int[] CheckedIds, int SeriesId)
        {
            await _userProfileService.CheckEpisodes(CheckedIds, SeriesId);
            return Json("Success");
        }
        [HttpPost]
        public async Task<float> SelectSeriesRaiting (int UserRaiting, int SeriesId)
        {
           return await _userProfileService.SelectSeriesRaiting(UserRaiting, SeriesId);
        }
        public async Task<JsonResult> UploadImage(IFormFile ImageFile)
        {
            if (ImageFile != null)
            {
                string path = Path.Combine("images", "UserAvatars", ImageFile.FileName);
                using (var fileStream = new FileStream(Path.Combine(_env.WebRootPath, path), FileMode.Create))
                {
                    await ImageFile.CopyToAsync(fileStream);
                }
                string UserSub = User.GetSub();
                UserProfile profile = await db.UserProfiles.FirstOrDefaultAsync(x => x.UserId == UserSub);
                profile.ImageSrc = path;
                db.Update(profile);
                await db.SaveChangesAsync();
            }
            return Json("Success");
        }
    }
}

Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/account.css" />
</head>
<body>
    <header>
    </header>
    <div class="body_wrapper">
        @RenderBody()
    </div>

    <footer>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/account.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NotMyShows</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav>
            <div class="nav-container">
                <a class="navbar-logo" asp-controller="Home" asp-action="Index">
                    <svg>
                        <use xlink:href="/Icons/logo-item.svg#logo_icon"></use>
                    </svg>
                </a>
                <div class="search-input-container">
                    <input class="search-input" placeholder="Поиск по сериалам" />
                    <button class="search-button">
                        <svg height="20" width="20">
                            <use xlink:href="/Icons/outline/20/search.svg#search_icon"></use>
                        </svg>
                    </button>
                </div>
                <div class="nav-profile-container">
                    <div class="nav-profile-buttons-container">
                        <button class="nav-profile-button">
                            <svg>
                                <use xlink:href="/Icons/outline/20/message.svg#message_icon"></use>
                            </svg>
                        </button>
                        <button class="nav-profile-button">
                            <svg id="notification-svg">
                                <use xlink:href="/Icons/outline/20/notification.svg#notification_icon"></use>
                            </svg>
                        </button>
                    </div>
                    <button class="premium-button">
                        Купить Premium
                    </button>
                    <div class="nav-profile-avatar-container">

                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="body-content">
        <aside class="sidebar-container">
            <nav class="sidebar-nav">
                <ul class="sidebar-menu-items">
                    <li class="menu-item">
                        <a asp-controller="Home" asp-action="Index">
                            <svg>
                                <use xlink:href="/Icons/outline/24/user.svg#user_icon"></use>
                            </svg>
                            Мой профиль
                        </a>
                    </li>
                    <li class="menu-item">
                        <a href="#">
                            <svg>
                                <use xlink:href="/Icons/outline/24/calendar.svg#calendar_icon"></use>
                            </svg>
                            Лента событий
                        </a>
                    </li>
                    <li class="menu-item">
                        <a asp-controller="Home" asp-action="SeriesCatalog">
                            <svg>
                                <use xlink:href="/Icons/outline/24/shows.svg#shows_icon"></use>
                            </svg>
                            Каталог сериалов
                        </a>
                    </li>
                    <li class="menu-item">
                        <a asp-controller="Home" asp-action="GetRecommendations">
                            <svg>
                                <use xlink:href="/Icons/outline/24/recommendations.svg#recommendations_icon"></use>
                            </svg>
                            Рекомендации
                        </a>
                    </li>
                    <li class="menu-item">
                        <a asp-controller="Profiles" asp-action="Friends">
                            <svg>
                                <use xlink:href="/Icons/outline/24/friends.svg#friends_icon"></use>
                            </svg>
                            Друзья
                        </a>
                    </li>
                    <li class="menu-item">
                        <a href="#">
                            <svg>
                                <use xlink:href="/Icons/outline/24/favorites.svg#favorites_icon"></use>
                            </svg>
                            Избранное
                        </a>
                    </li>
                    <li class="menu-item">
                        <a href="#">
                            <svg>
                                <use xlink:href="/Icons/outline/24/achievements.svg#achievements_icon"></use>
                            </svg>
                            Мои достижения
                        </a>
                    </li>
                    <li class="menu-item">
                        <a href="#">
                            <svg>
                                <use xlink:href="/Icons/outline/24/news.svg#news_icon"></use>
                            </svg>
                            Новости
                        </a>
                    </li>
                </ul>
                <ul class="secondary-links">
                    <li class="link-item">
                        <a href="#">
                            Реклама
                        </a>
                        <a href="#">
                            Контакты
                        </a>
                    </li>
                    <li class="link-item">
                        <a href="#">
                            Частые вопросы
                        </a>
                        <a href="#">
                            Ещё
                        </a>
                    </li>
                </ul>
            </nav>
        </aside>
        <main role="main" class="main-render-body">
            @RenderBody()
        </main>
    </div>

    @*<footer>
        <div class="container">
            &copy; 2020 - NeMyshowsNew - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>