Models/UserProfile.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace NotMyShows.Models
{
    public class UserProfile
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public User User { get; set; }
        public string ImageSrc { get; set; }
        public List<UserSeries> UserSeries { get; set; }
        public List<UserEpisodes> UserEpisodes { get; set; }
        public List<UserRecommendation> UserRecommendations { get; set; }
        public List<Friend> Friends { get; set; }
        public List<Comment> Comments { get; set; }
        public UserProfile()
        {
            UserSeries = new List<UserSeries>();
            UserEpisodes = new List<UserEpisodes>();
            UserRecommendations = new List<UserRecommendation>();
        }
    }
    public class UserRecommendation
    {
        public int SeriesId { get; set; }
        public Series Series { get; set; }
        public int UserProfileId { get; set; }
        public UserProfile UserProfile { get; set; }
        public float PotentialRating { get; set; }
        public DateTime Date { get; set; }
    }
    public class Friend
    {
        public int Id { get; set; }
        public int UserProfileId { get; set; }
        public UserProfile UserProfile { get; set; }
        public int FriendProfileId { get; set; }
        [NotMapped]
        public UserProfile FriendProfile { get; set; }
        public DateTime Date { get; set; }
    }
    public class UserSeries
    {
        public int SeriesId { get; set; }
        public Series Series { get; set; }
        public int UserProfileId { get; set; }
        public UserProfile UserProfile { get; set; }
        public int UserRaiting { get; set; }
        public DateTime RaitingDate { get; set; }
        public int WatchStatusId { get; set; }
        public WatchStatus WatchStatus { get; set; }
        public DateTime StatusChangedDate { get; set; }
    }
    public class UserEpisodes
    {
        public int EpisodeId { get; set; }
        public Episode Episode { get; set; }
        public int UserProfileId { get; set; }
        public UserProfile UserProfile { get; set; }
        public DateTime WatchDate { get; set; }
    }
    public class WatchStatus
    {
        public int Id { get; set; }
        public string StatusName { get; set; }
        public List<UserSeries> UserSeries { get; set; }
        public WatchStatus()
        {
            UserSeries = new List<UserSeries>();
        }
    }
    public class Comment
    {
        public int Id { get; set; }
        public int UserProfileId { get; set; }
        public UserProfile UserProfile { get; set; }
        public int EpisodeId { get; set; }
        public Episode Episode { get; set; }
        public string Text { get; set; }
        public int Likes { get; set; }
        public int Dislikes { get; set; }
        public DateTime Date { get; set; }
    }
}

Controllers/UserProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NotMyShows.Models;
using NotMyShows.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace NotMyShows.Controllers
{
    [Authorize]
    public class UserProfileController : Controller
    {
        readonly SeriesContext db;
        readonly private IHostingEnvironment _env;
        public UserProfileController(SeriesContext context, IHostingEnvironment env)
        {
            db = context;
            _env = env;
        }
        public async Task<IActionResult> Profiles()
        {
            List<WatchStatus> watchStatuses = await db.WatchStatuses.ToListAsync();
            UserProfile profile = await GetUserProfile(true);
            List<WatchStatusTab> statusTabs = new List<WatchStatusTab>();
            int Hours = 0;
            foreach (var status in watchStatuses)
            {
                List<ProfileSeriesItem> TabSeriesList = new List<ProfileSeriesItem>();
                foreach (var item in profile.UserSeries.Where(x=>x.WatchStatusId == status.Id))
                {
                    ProfileSeriesItem seriesItem = new ProfileSeriesItem
                    {
                        Id = item.Series.Id,
                        Title = item.Series.Title,
                        OriginalTitle = item.Series.OriginalTitle,
                        EpisodesCount = item.Series.Episodes.Count(),
                        Status = new SeriesStatus
                        {
                            Name = StatusColor.GetNewStatusName(item.Series.Status.Name),
                            StatusColorName = StatusColor.GetColor(item.Series.Status.Name)
                        },
                        PicturePath = item.Series.PicturePath,
                        WatchedEpisodesCount = profile.UserEpisodes.Where(x => x.Episode.SeriesId == item.Series.Id).Count(),
                        UserRaiting = item.UserRaiting
                    };
                    Hours += seriesItem.WatchedEpisodesCount * item.Series.EpisodeTime;
                    TabSeriesList.Add(seriesItem);
                }
                WatchStatusTab tab = new WatchStatusTab
                {
                    WatchStatus = status,
                    SeriesList = TabSeriesList
                };
                statusTabs.Add(tab);
            }
            ProfileStats profileStats = new ProfileStats
            {
                EpisodesCount = profile.UserEpisodes.Count(),
                SeriesCount = statusTabs.FirstOrDefault(x=>x.WatchStatus.StatusName == "Просмотрено").SeriesList.Count(),
                HoursSpent = Hours,
                AchievementsCount = 0
            };
            profile.UserSeries = null;
            UserProfileViewModel model = new UserProfileViewModel
            {
                UserProfile = profile,
                StatusTabs = statusTabs,
                ProfileStats = profileStats
            };
            return View(model);
        }
        public async Task<UserProfile> GetUserProfile(bool IncludeSeries)
        {
            string UserSub = User.GetSub();
            UserProfile profile = new UserProfile();
            if (IncludeSeries)
            {
                profile = await db.UserProfiles
                    .Include(us => us.UserSeries).ThenInclude(s => s.Series).ThenInclude(s => s.Status)
                    .Include(us => us.UserSeries).ThenInclude(s => s.Series).ThenInclude(e => e.Episodes)
                    .Include(ue => ue.UserEpisodes).ThenInclude(e => e.Episode)
                    .FirstOrDefaultAsync(x => x.UserSub == UserSub);
            }
            else
            {
                profile = await db.UserProfiles.FirstOrDefaultAsync(x => x.UserSub == UserSub);
            }
            return profile;
        }
        public async Task<IActionResult> Series(int SeriesId)
        {
            Series series = await db.Series.Include(r => r.Raiting).Include(s => s.Status).Include(ch => ch.Channel)
                .Include(c => c.Country).Include(sg => sg.SeriesGenres).ThenInclude(g => g.Genre).Include(e => e.Episodes)
                .FirstOrDefaultAsync(x => x.Id == SeriesId);
            UserProfile profile = await GetUserProfile(true);
            var userSeries = profile.UserSeries.FirstOrDefault(x => x.SeriesId == SeriesId);
            string CurrentWatchStatus = "";
            int UserRaiting = 0;
            List<EpisodeCheckBox> episodes = new List<EpisodeCheckBox>();
            if (userSeries != null)
            {
                var watchStatus = await db.WatchStatuses.FirstOrDefaultAsync(x => x.Id == userSeries.WatchStatusId);
                foreach (var episode in series.Episodes)
                {
                    EpisodeCheckBox episodeCheckBox = new EpisodeCheckBox
                    {
                        Episode = episode,
                        isChecked = profile.UserEpisodes.FirstOrDefault(x => x.EpisodeId == episode.Id) == null ? false : true
                    };
                    episodes.Add(episodeCheckBox);
                }
                CurrentWatchStatus = watchStatus.StatusName;
                UserRaiting = userSeries.UserRaiting;
            }
            else
            {
                foreach (var episode in series.Episodes)
                {
                    EpisodeCheckBox episodeCheckBox = new EpisodeCheckBox
                    {
                        Episode = episode,
                        isChecked = false
                    };
                    episodes.Add(episodeCheckBox);
                }
            }
            episodes.Sort((x, y) => DateTime.Compare(x.Episode.Date ?? DateTime.MaxValue, y.Episode.Date ?? DateTime.MaxValue));
            SeriesView model = new SeriesView
            {
                StatusColorName = StatusColor.GetColor(series.Status.Name),
                Series = series,
                CurrentWatchStatus = CurrentWatchStatus,
                Episodes = episodes,
                UserRaiting = UserRaiting
            };
            model.Series.Status.Name = StatusColor.GetNewStatusName(series.Status.Name);
            //if (series == null)
            //{
            //    return StatusCode(StatusCodes.Status404NotFound);
            //}
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> SelectWatchStatus(int SeriesId, string StatusName)
        {
            string UserSub = User.GetSub();
            UserProfile userProfile = await db.UserProfiles.Include(us=>us.UserSeries).FirstOrDefaultAsync(x => x.UserSub == UserSub);
            if (userProfile != null)
            {
                WatchStatus status = await db.WatchStatuses.FirstOrDefaultAsync(x => x.StatusName == StatusName);
                UserSeries userSeries = userProfile.UserSeries.FirstOrDefault(x => x.SeriesId == SeriesId);
                if (userSeries != null && userSeries.WatchStatusId == status.Id)
                {
                    //userProfile.UserSeries.Remove(userSeries);
                    userSeries.WatchStatus = await db.WatchStatuses.FirstOrDefaultAsync(x => x.StatusName == "Брошено");
                }
                if(userSeries != null && userSeries.WatchStatusId != status.Id)
                {
                    userSeries.WatchStatus = status;
                    db.Update(userSeries);
                }
                if(userSeries == null)
                {
                    userSeries = new UserSeries
                    {
                        SeriesId = SeriesId,
                        WatchStatus = status,
                        StatusChangedDate = DateTime.Now
                    };
                    userProfile.UserSeries.Add(userSeries);
                    db.Update(userProfile);
                }
                await db.SaveChangesAsync();
            }
            return Json("Success");
        }
        public async Task SelectDefaultWatchStatus(int SeriesId, UserProfile UserProfile, string StatusName)
        {
            UserSeries userSeries = UserProfile.UserSeries.FirstOrDefault(x => x.SeriesId == SeriesId);
            WatchStatus status = await db.WatchStatuses.FirstOrDefaultAsync(x => x.StatusName == StatusName);
            if (userSeries == null)
            {
                userSeries = new UserSeries
                {
                    SeriesId = SeriesId,
                    WatchStatus = status,
                    StatusChangedDate = DateTime.Now
                };
                UserProfile.UserSeries.Add(userSeries);
            }
            if (userSeries != null && userSeries.WatchStatusId != status.Id)
            {
                userSeries.WatchStatus = status;
            }
            db.Update(UserProfile);
            await db.SaveChangesAsync();
        }
        public async Task IsSeriesWatchCompleted(UserProfile UserProfile, int SeriesId)
        {
            Series series = await db.Series.Include(e => e.Episodes).FirstOrDefaultAsync(x => x.Id == SeriesId);
            int EpisodesCount = series.Episodes.Count();
            int WatchedEpisodesCount = UserProfile.UserEpisodes.Where(x => x.Episode.SeriesId == SeriesId).Count();
            if(EpisodesCount == WatchedEpisodesCount)
            {
                await SelectDefaultWatchStatus(SeriesId, UserProfile, "Просмотрено");
            }
            else
            {
                await SelectDefaultWatchStatus(SeriesId, UserProfile, "Смотрю");
            }
        }
        [HttpPost]
        public async Task<IActionResult> CheckEpisode(int EpisodeId, int SeriesId)
        {
            string UserSub = User.GetSub();
            UserProfile userProfile = await db.UserProfiles.Include(us => us.UserSeries)

Views/UserProfile/UserProfile.cshtml
@model NotMyShows.ViewModel.UserProfileViewModel
@{
    ViewData["Title"] = "Profiles";
}
<link rel="stylesheet" href="~/css/UserProfile.css" />
<link rel="stylesheet" href="~/css/SeriesSearch.css" />
@if (User.Identity.IsAuthenticated)
{
    <a asp-controller="Home" asp-action="Logout">
        Выход
    </a>
}
<div class="profile-container">
    <div class="user-info">
        <div class="user-avatar">
            <label for="upload-image">
                <img id="avatar-img" src="\@Html.Raw(Model.UserProfile.ImageSrc)" />
            </label>
            <input id="upload-image" type="file" />
        </div>
        <div class="user-name">
            @User.GetName()
        </div>
        <div class="user-raiting">
            +11777
        </div>
    </div>
    <div class="separator">

    </div>
    <div class="user-stats">
        <div class="stat-item">
            <div class="stat-number">
                @Model.ProfileStats.EpisodesCount.ToString("N0")
            </div>
            <div class="stat-name">
                Просмотрено эпизодов
            </div>
        </div>
        <div class="stat-item">
            <div class="stat-number">
                @Model.ProfileStats.SeriesCount.ToString("N0")
            </div>
            <div class="stat-name">
                Просмотрено сериалов
            </div>
        </div>
        <div class="stat-item">
            <div class="stat-number">
                @Model.ProfileStats.HoursSpent.ToString("N0")
            </div>
            <div class="stat-name">
                Потрачено часов
            </div>
        </div>
        <div class="stat-item">
            <div class="stat-number">
                @((Model.ProfileStats.HoursSpent/24).ToString("N0"))
            </div>
            <div class="stat-name">
                Потрачено дней
            </div>
        </div>
        <div class="stat-item">
            <div class="stat-number">
                @Model.ProfileStats.AchievementsCount
            </div>
            <div class="stat-name">
                Получено достижений
            </div>
        </div>
    </div>
</div>
<div class="user-series">
    <div class="series-tabs" data="Смотрю">
        @foreach (var item in Model.StatusTabs)
        {
            <div class="tab-item">
                <input id="@item.WatchStatus.Id" type="radio" name="radio" value="@item.WatchStatus.StatusName">
                <label for="@item.WatchStatus.Id">
                    <span class="watch-status-name">@item.WatchStatus.StatusName</span>
                    <span class="watch-status-count">@item.SeriesList.Count()</span>
                </label>
            </div>
        }
    </div>
    <div>
        @foreach (var tab in Model.StatusTabs)
        {
            <div id="@tab.WatchStatus.StatusName" class="profile-series-cards-container" style="display: none">
                @foreach (var series in tab.SeriesList)
                {
                    <a class="series-search-card profile-series-card" asp-controller="UserProfile" asp-action="Series" asp-route-SeriesId="@series.Id">
                        <div class="series-cover-container">
                            <img src="\@Html.Raw(series.PicturePath)" class="series-cover" />
                            <div class="series-status" style="background-color:@series.Status.StatusColorName">
                                @series.Status.Name
                            </div>
                        </div>
                        <div class="series-titles-container">
                            <label class="series-russian-title">@series.OriginalTitle</label>
                            <label class="series-origin-title">@series.Title</label>
                        </div>
                        <div class="series-raiting-progress-container">
                            <div class="series-raiting">
                                <svg>
                                    <use xlink:href="/Icons/outline/24/star.svg#star_icon"></use>
                                </svg>
                                <div class="series-raiting-number">
                                    @series.UserRaiting
                                </div>
                            </div>
                            <div class="series-progress">
                                @{
                                    int progress = (int)(100 * ((double)series.WatchedEpisodesCount / series.EpisodesCount));
                                }
                                <progress max="100" value="@progress"></progress>
                                <div class="progress-count">@series.WatchedEpisodesCount/@series.EpisodesCount</div>
                            </div>
                        </div>
                    </a>
                }
            </div>
        }
    </div>
</div>